#:schema node_modules/wrangler/config-schema.json
name = "react-summit-cloudflare-fullstack-workshop-nov2024"
compatibility_date = "2024-10-11"
pages_build_output_dir = "./build/client"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "KV"
id = "<namespace-id>"

# Note: if you are not using R2 as part of your implementation
#       you should remove or comment out this binding
#       (this bindings is not a problem for local development
#       but deplyoing your application with it would fail)
[[r2_buckets]]
binding = "R2"
bucket_name = "<bucket-name>"
